
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:password@db:5432/library
    depends_on:
      - db

  book-service:
    build: ./book-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:password@db:5432/library
    depends_on:
      - db

  borrowing-service:
    build: ./borrowing-service
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:password@db:5432/library
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
